const PostModalActionType = {
  SHOW_POST_MODAL: 'SHOW_MODAL',
  HIDE_POST_MODAL: 'HIDE_MODAL',
  EDIT_POST: 'EDIT_POST',
  DELETE_POST: 'DELETE_POST',
  SHOW_DELETE_MODAL: 'SHOW_DELETE_MODAL',
  HIDE_DELETE_MODAL: 'HIDE_DELETE_MODAL'
};

export default PostModalActionType;